### ISSUE TITLE
Parameters passed when running the jar file

### ISSUE THREAD

**Issue by EFregnan** [wogscpar/SZZUnleashed#15]
I may be totally wrong here, but it seems to me that _Configuration.java_ supports more parameters than the two specified in _Readme.md_ for the _szz_find_bug_introducers-<version_number>.jar_ file.
Maybe an explanation about them should be added in the _Readme.md_ file. 

In particular, I think that it may be important to explain the parameter that sets the number of cores during the execution. Currently, the _Readme.md_ file states: 

> The algorithm tries to use as many cores as possible during runtime.

However, the option to enable the user to set the number of cores seems to have been implemented in _Configuration.java_. I think this possibility should be explained in _Readme.md_ since it may be relevant for the users.

What do you think?

**Comment by wogscpar** [comment]
I'm not sure. At first I thought of not giving the user the opportunity to choose the number of cores since the algorithm will run as fast as possible always. If the user wants to change the number of cores, the algorithm itself will provide them with the sufficient information when executed with the **--help** argument. However, it could be a good idea to write a more advanced example of the algorithm which doesn't lay in the main README.md but in a separate directory.

**Comment by EFregnan** [comment]
Ok. I agree, we should include explanations about these extra parameters in an example. We can probably add it in the _examples_ directory we mentioned in PR #10.

**Comment by wogscpar** [comment]
I've added some explanations for some parameters in [the examples directory](https://github.com/wogscpar/SZZUnleashed/tree/master/examples).
